INFO: Default loss without VGG
INFO: 2023-07-25 20:56:15 Argument batch_size: 8
INFO: 2023-07-25 20:56:15 Argument code_test: True
INFO: 2023-07-25 20:56:15 Argument data_train_path: ./../data/data_96/train/
INFO: 2023-07-25 20:56:15 Argument device_number: 3
INFO: 2023-07-25 20:56:15 Argument epoch: 1
INFO: 2023-07-25 20:56:15 Argument local_rank: 0
INFO: 2023-07-25 20:56:15 Argument max_HiC: 200
INFO: 2023-07-25 20:56:15 Argument num_gpu: 1
INFO: 2023-07-25 20:56:15 Argument num_workers: 1
INFO: 2023-07-25 20:56:15 Argument resume_epoch: 0
INFO: 2023-07-25 20:56:15 Argument resume_path: None
INFO: 2023-07-25 20:56:15 Argument rgb: False
INFO: 2023-07-25 20:56:15 Argument train_dataset: hic
INFO: 2023-07-25 20:56:15 Argument val_datasets: ['hic']
INFO: Traceback:
INFO: Traceback (most recent call last):
  File "./train_1d.py", line 297, in <module>
    train(model, args)
  File "./train_1d.py", line 151, in train
    print("dataset[0][1][100]: ", dataset[0][1][100])
IndexError: index 100 is out of bounds for axis 0 with size 96

INFO: Sys.exc_info()[2]:
INFO: <traceback object at 0x7fe558185440>
