INFO: Default loss without VGG
INFO: No cutoff
INFO: 2023-08-21 13:44:38 Argument batch_size: 8
INFO: 2023-08-21 13:44:38 Argument code_test: True
INFO: 2023-08-21 13:44:38 Argument data_train_path: ./../data/data_96/train/
INFO: 2023-08-21 13:44:38 Argument data_val_path: ./../data/data_96/val/data_val_chr19_96.npy
INFO: 2023-08-21 13:44:38 Argument device_number: 1
INFO: 2023-08-21 13:44:38 Argument epoch: 1
INFO: 2023-08-21 13:44:38 Argument local_rank: 0
INFO: 2023-08-21 13:44:38 Argument loss: single_channel_no_vgg
INFO: 2023-08-21 13:44:38 Argument max_HiC: 255
INFO: 2023-08-21 13:44:38 Argument num_gpu: 1
INFO: 2023-08-21 13:44:38 Argument num_workers: 1
INFO: 2023-08-21 13:44:38 Argument patch_size: 96
INFO: 2023-08-21 13:44:38 Argument resume_epoch: 0
INFO: 2023-08-21 13:44:38 Argument resume_path: None
INFO: 2023-08-21 13:44:38 Argument rgb: False
INFO: 2023-08-21 13:44:38 Argument train_dataset: hic
INFO: 2023-08-21 13:44:38 Argument val_datasets: ['hic']
INFO: 2023-08-21 13:44:42 epoch:0 dataset: 1/17 step: 0/155 time:0.57+2.12 loss_avg:2.2300e-01
INFO: 2023-08-21 13:44:43 epoch:0 dataset: 1/17 step: 1/155 time:0.00+0.87 loss_avg:1.8877e-01
INFO: Training on data_train_chr7_96.npy complete.
INFO: 2023-08-21 13:44:44 epoch:0 dataset: 2/17 step: 0/90 time:0.50+0.80 loss_avg:2.5133e-01
INFO: 2023-08-21 13:44:45 epoch:0 dataset: 2/17 step: 1/90 time:0.00+0.72 loss_avg:2.4228e-01
INFO: Traceback:
INFO: Traceback (most recent call last):
  File "./train_1d.py", line 314, in <module>
    train(model, args)
  File "./train_1d.py", line 203, in train
    evaluate(model, val_data, dataset_name, epoch, step)
NameError: name 'dataset_name' is not defined

INFO: Sys.exc_info()[2]:
INFO: <traceback object at 0x7fac88398200>
